title: DecentChat
description: A global decentralized P2P chat network.
show_downloads: true
theme: jekyll-theme-midnight

github:
     repository_url: https://github.com/IshaanRaja/DecentChat
     tar_url: https://github.com/IshaanRaja/DecentChat/tarball/main
     zip_url: https://github.com/IshaanRaja/DecentChat/zipball/main
